-- Run this in Supabase: SQL Editor → New query
-- Creates the waitlist table used by the app

create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text not null unique,
  role text not null,
  city text,
  category text,
  created_at timestamptz not null default now()
);

-- Optional: enable Row Level Security (RLS) if you want per-user rules later.
-- For server-side service_role access, RLS is bypassed by default.
-- alter table public.waitlist enable row level security;
